/**
 * Terminal colour themes.
 *
 * WHY EVERY COLOUR RULE IN HERE IS `!important`
 * ---------------------------------------------
 * The prompt characters, the echoed command, the `help` rows, the idle line and
 * the links are all painted from JavaScript in terminal-utils.ts — e.g.
 * `promptSpan1.style.color = "#ff9e64"`. Those are INLINE styles, and an inline
 * style beats every selector in a stylesheet no matter how specific it is. The
 * only thing that outranks an inline style is `!important`, so every declaration
 * below that has to fight one carries it. Remove the `!important` and the theme
 * silently does nothing to the prompt — the terminal keeps its Tokyo Night
 * orange/purple/cyan on a green background, which looks broken.
 *
 * (The page and terminal backgrounds are class-based, but they are also marked
 * `!important` because the site's own <style> block lives in the <body> — later
 * in the document than this one — and would otherwise win on source order.)
 */

export type ThemeName = "tokyo" | "phosphor" | "amber";

/** The single <style> element this module owns. Never duplicated. */
const STYLE_ID = "terminal-theme";

const NAMES: ThemeName[] = ["tokyo", "phosphor", "amber"];

interface Palette {
    /** html/body background. */
    readonly page: string;
    /** .terminal__content background (sits over `page`, so it may be translucent). */
    readonly body: string;
    readonly titleBar: string;
    readonly titleText: string;
    readonly titleBorder: string;
    readonly dotClose: string;
    readonly dotHide: string;
    readonly dotResize: string;
    /** λ — the brightest thing on screen. */
    readonly bright: string;
    /** Display text and the `~` segment. */
    readonly text: string;
    /** `>>` and the echoed command. */
    readonly mid: string;
    /** Path segment, help descriptions, idle nudge, hints. */
    readonly dim: string;
    readonly link: string;
    readonly caret: string;
    /** .terminal__input.valid-command */
    readonly ok: string;
    /** Phosphor bloom for ordinary text. */
    readonly glow: string;
    /** Phosphor bloom for the prompt. */
    readonly glowStrong: string;
    /** Scanline colour laid over the terminal body. Kept faint on purpose. */
    readonly scanline: string;
    /** Deadpan line the terminal prints back. */
    readonly status: string;
}

/** P1 green CRT. Near-black with a green cast, three steps of green, real bloom. */
const PHOSPHOR: Palette = {
    page: "#050b06",
    body: "rgba(3, 13, 5, 0.72)",
    titleBar: "#0d2413",
    titleText: "#9dffc0",
    titleBorder: "#1e5c30",
    dotClose: "#1d5c33",
    dotHide: "#2fa85a",
    dotResize: "#63f78f",
    bright: "#b6ffd0",
    text: "#55ef8c",
    mid: "#33d96a",
    dim: "#23a955",
    link: "#7dffd6",
    caret: "#b6ffd0",
    ok: "#daffe9",
    glow: "0 0 2px rgba(85, 239, 140, 0.45), 0 0 9px rgba(51, 217, 106, 0.25)",
    glowStrong: "0 0 3px rgba(182, 255, 208, 0.7), 0 0 12px rgba(85, 239, 140, 0.4)",
    scanline: "rgba(0, 0, 0, 0.16)",
    status: "theme: phosphor. P1 green. Burn-in included at no extra cost.",
};

/** P3 amber monitor. Same idea, warmer, marginally kinder to the eyes. */
const AMBER: Palette = {
    page: "#0b0703",
    body: "rgba(16, 9, 2, 0.72)",
    titleBar: "#241605",
    titleText: "#ffd9a0",
    titleBorder: "#5c3a12",
    dotClose: "#5c3a12",
    dotHide: "#a8701d",
    dotResize: "#ffb648",
    bright: "#ffd9a0",
    text: "#ffb648",
    mid: "#e8952a",
    dim: "#cc8226",
    link: "#ffe07a",
    caret: "#ffd9a0",
    ok: "#fff1d6",
    glow: "0 0 2px rgba(255, 182, 72, 0.45), 0 0 9px rgba(232, 149, 42, 0.25)",
    glowStrong: "0 0 3px rgba(255, 217, 160, 0.7), 0 0 12px rgba(255, 182, 72, 0.4)",
    scanline: "rgba(0, 0, 0, 0.16)",
    status: "theme: amber. P3 phosphor. Easier on the eyes, allegedly.",
};

function paletteFor(name: string): Palette | null {
    if (name === "phosphor") return PHOSPHOR;
    if (name === "amber") return AMBER;
    return null;
}

function buildCss(p: Palette, name: string): string {
    return `/* terminal theme: ${name} — generated by src/utils/themes.ts */
/* !important everywhere on purpose: terminal-utils.ts sets the prompt, echo and
   link colours as INLINE styles from JS, and only !important outranks those. */

html,
body {
    background-color: ${p.page} !important;
}

.terminal__content {
    background-color: ${p.body} !important;
    /* faint scanlines: enough to read as a CRT, not enough to hurt the text */
    background-image: repeating-linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0) 0px,
        rgba(0, 0, 0, 0) 2px,
        ${p.scanline} 2px,
        ${p.scanline} 3px
    ) !important;
    box-shadow: rgba(0, 0, 0, 0.55) 0px 5px 18px !important;
}

.terminal__title-container {
    background-color: ${p.titleBar} !important;
    color: ${p.titleText} !important;
    border-bottom: 1px solid ${p.titleBorder} !important;
    text-shadow: ${p.glow};
}

.close-button {
    background-color: ${p.dotClose} !important;
}

.hide-button {
    background-color: ${p.dotHide} !important;
}

.resize-button {
    background-color: ${p.dotResize} !important;
}

.terminal__display {
    color: ${p.text} !important;
    text-shadow: ${p.glow};
}

/* λ. The static markup uses -promt-1, but handleKeyUp() reuses -promt-2 for BOTH
   the λ and the ~ of an echoed row, so the λ is picked out as the row's first
   span — otherwise the two would be forced to the same colour. */
.terminal__input_container-promt-1,
.output-container .terminal__input_container-promt-2:first-child {
    color: ${p.bright} !important;
    text-shadow: ${p.glowStrong};
}

/* ~ */
.terminal__input_container-promt-2 {
    color: ${p.text} !important;
    text-shadow: ${p.glow};
}

/* >> */
.terminal__input_container-promt-3 {
    color: ${p.mid} !important;
    text-shadow: ${p.glow};
}

/* current path — live row (-promt-4) and echoed row (-promt-location) */
.terminal__input_container-promt-4,
.terminal__input_container-promt-location {
    color: ${p.dim} !important;
    text-shadow: ${p.glow};
}

/* the command echoed back above its output */
.command-input {
    color: ${p.mid} !important;
    text-shadow: ${p.glow};
}

.terminal__input {
    color: ${p.text} !important;
    caret-color: transparent !important;
    text-shadow: ${p.glow}

.terminal__cursor {
    background-color: ${p.caret} !important;
};
}

.terminal__input.valid-command {
    color: ${p.ok} !important;
}

.terminal__display a,
.terminal__display a:visited {
    color: ${p.link} !important;
    text-shadow: ${p.glow};
}

.terminal__display a:hover {
    color: ${p.bright} !important;
    text-shadow: ${p.glowStrong};
}

/* two-column rows printed by displaySidesBlock(): a div per command, name on the
   left, description on the right. Neither carries a class, so they are reached
   structurally — help rows are the only divs nested two deep in the display. */
.terminal__display > div > div {
    color: ${p.text} !important;
}

.terminal__display > div > div > span:last-child {
    color: ${p.dim} !important;
}

/* the idle nudge line. Its only handle is the inline colour #565f89, which the
   browser serialises as rgb(86, 95, 137). */
.terminal__display div[style*="rgb(86, 95, 137)"] {
    color: ${p.dim} !important;
}

.hints {
    color: ${p.dim} !important;
}

.terminal__display-container::-webkit-scrollbar {
    width: 8px;
}

.terminal__display-container::-webkit-scrollbar-thumb {
    background-color: ${p.dim};
    border-radius: 4px;
}

.terminal__display-container::-webkit-scrollbar-track {
    background-color: transparent;
}

.terminal ::selection {
    background-color: ${p.mid};
    color: ${p.page};
}
`;
}

/** Returns the single <style id="terminal-theme">, creating it once if needed. */
function themeStyleElement(): HTMLStyleElement {
    const existing = document.getElementById(STYLE_ID);
    if (existing instanceof HTMLStyleElement) return existing;
    if (existing) existing.remove();

    const element = document.createElement("style");
    element.id = STYLE_ID;
    document.head.appendChild(element);
    return element;
}

/**
 * Applies a theme and returns the line the terminal should print.
 * "tokyo" removes the override and restores the site default.
 */
const STORAGE_KEY = "terminal-theme";
const HINTS_STYLE_ID = "terminal-theme-hints";

/**
 * The hint line lives inside <my-hints>'s shadow root, so the document
 * stylesheet cannot reach it — a plain `.hints` rule there is dead CSS. Inject a
 * copy into the shadow root instead. Its two key spans get inline colours
 * rewritten on every rotation, so these need !important to stick.
 */
function paintHints(palette: Palette | null): void {
    const host = document.querySelector("my-hints");
    const root = host?.shadowRoot;
    if (!root) return;

    const existing = root.querySelector(`#${HINTS_STYLE_ID}`);

    if (!palette) {
        existing?.remove();
        return;
    }

    const style = existing instanceof HTMLStyleElement ? existing : document.createElement("style");
    style.id = HINTS_STYLE_ID;
    style.textContent = `
        .hints { color: ${palette.dim} !important; text-shadow: ${palette.glow} !important; }
        .hints span:nth-of-type(1) { color: ${palette.bright} !important; }
        .hints span:nth-of-type(2) { color: ${palette.mid} !important; }
    `;

    if (!style.isConnected) root.appendChild(style);
}

/**
 * <my-hints> is appended after the terminal, so on first load it does not exist
 * yet when the stored theme is restored. Retry briefly rather than racing it.
 */
function paintHintsWhenReady(palette: Palette | null): void {
    paintHints(palette);
    setTimeout(() => paintHints(palette), 0);
    setTimeout(() => paintHints(palette), 300);
}

/** Storage can throw in private mode, and a theme is not worth an exception. */
function remember(key: string): void {
    try {
        localStorage.setItem(STORAGE_KEY, key);
    } catch {
        /* ignore */
    }
}

export function applyTheme(name: string): string {
    const key = name.trim().toLowerCase();

    if (key === "tokyo") {
        const existing = document.getElementById(STYLE_ID);
        if (existing) existing.remove();
        paintHintsWhenReady(null);
        remember(key);
        return "theme: tokyo. Default restored. Nothing happened here.";
    }

    const palette = paletteFor(key);
    if (!palette) {
        return `Unknown theme '${name}'. Available: ${themeNames().join(", ")}.`;
    }

    themeStyleElement().textContent = buildCss(palette, key);
    paintHintsWhenReady(palette);
    remember(key);
    return palette.status;
}

/**
 * Reapplies the last chosen theme on load, so a reload does not silently throw
 * the choice away. Silent by design: nothing is printed to the terminal.
 */
export function restoreTheme(): void {
    let stored: string | null = null;
    try {
        stored = localStorage.getItem(STORAGE_KEY);
    } catch {
        return;
    }

    if (!stored || stored === "tokyo") return;

    const palette = paletteFor(stored);
    if (!palette) return;

    themeStyleElement().textContent = buildCss(palette, stored);
    paintHintsWhenReady(palette);
}

export function themeNames(): string[] {
    return [...NAMES];
}
